# ====================================
# DATASOURCE CONFIGURATION (Render)
# ====================================
spring.datasource.url=jdbc:postgresql://dpg-d4ajtii4d50c73cm2mv0-a.oregon-postgres.render.com:5432/cultivapp
spring.datasource.username=cultivapp_user
spring.datasource.password=91BDiVQZpFLJkBtDHkqXZ8pRbpk53uR6
spring.datasource.driver-class-name=org.postgresql.Driver

# ====================================
# JPA / HIBERNATE SETTINGS
# ====================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ====================================
# SERVER PORT (Render usa variable dinámica)
# ====================================
server.port=${PORT:8080}
